version: '3.2'
services:
  vue-app:
    build:
      context: .
    ports:
      - '5173:5173'
    volumes:
      - '.:/app'
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge
